server:
  address: 127.0.0.1
  port: 8080


management:
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true

spring:
  data:
    neo4j:
      password: SDAS
      uri: http://localhost:7474
      username: neo4j

sdas:
  cron: 0 * * * * ?
  dataProvider: twitter
  tags:
    - '#spring'
    - '#angular'
