server:
  address: 127.0.0.1
  port: 8080


management:
  endpoint:
    shutdown:
      enabled: true
endpoints:
  shutdown:
    enabled: true

spring:
  data:
    neo4j:
      password: SDAS
      uri: http://localhost:7474
      username: neo4j

sdas:
  cron: 0 */15 * ? * *
  dataProvider: twitter
  tags:
    - '#wybory'
    - '#polityka'
    - '#parlamenteuropejski'
    - '#europarlament'
    - '#wyboryparlamentarne'
    - '#kampaniawyborcza'
    - '#koalicjaeuropejska'
    - '#PiS'
    - '#PO'
    - '#SLD'
    - '#PSL'
    - '#Nowoczesna'
    - '#kukiz15'
    - '#wiosnabiedronia'
    - '#piatkabiedronia'
    - '#polskasercemeuropy'
    - '#piatkakaczynskiego'
    - '#lewicarazem'
    - '#tymrazemglosuje'
    - '#akcjaewakuacja'
    - '#election'
    - '#eu'
    - '#europe'
    - '#vote'
    - '#ep2019'
    - '#EUelections2019'
    - '#OurVoteOurRights'
    - '#IamEuropean'

